# Generated by Django 4.0.4 on 2022-06-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('icon', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'menus',
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('month_name', models.CharField(max_length=50)),
                ('month_id', models.IntegerField()),
            ],
            options={
                'db_table': 'months',
            },
        ),
    ]
