# Generated by Django 4.0.4 on 2022-05-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_assigned_to_alter_ticket_issued_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='closed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='is_closed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='is_opened',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='opened_at',
            field=models.DateTimeField(null=True),
        ),
    ]
