# Generated by Django 4.0.4 on 2022-05-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_ticket_assigned_to_alter_ticket_opened_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
