# Generated by Django 4.0.4 on 2022-05-26 18:49

from django.db import migrations, models
import tickets.models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_ticket_closed_at_alter_ticket_opened_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='attachment',
            field=models.ImageField(blank=True, upload_to=tickets.models.Ticket.avatar_directory_path),
        ),
    ]
