# Generated by Django 4.0.4 on 2022-05-26 20:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticket_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 5, 26, 20, 21, 19, 54149, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
