# Generated by Django 4.0.4 on 2022-06-01 18:16

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tickets.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0009_ticket_closed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='attachment',
            field=models.ImageField(blank=True, upload_to=tickets.models.Comment.avatar_directory_path),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='issued_by',
            field=models.ForeignKey(default=account.models.User, on_delete=django.db.models.deletion.DO_NOTHING, related_name='issued_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
