# Generated by Django 4.0.4 on 2022-06-20 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticketpriority_table'),
        ('tickets', '0011_alter_comment_attachment'),
    ]

    operations = [
    ]
